//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baichador.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MAX_THREADS {
            get {
                return ((int)(this["MAX_THREADS"]));
            }
            set {
                this["MAX_THREADS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MAX_RETRIES {
            get {
                return ((int)(this["MAX_RETRIES"]));
            }
            set {
                this["MAX_RETRIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--no-playlist -o \"{0}{1}.%(ext)s\" -qx --audio-format mp3 \"{2}\"")]
        public string CMD_NORMAL {
            get {
                return ((string)(this["CMD_NORMAL"]));
            }
            set {
                this["CMD_NORMAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--yes-playlist --flat-playlist --dump-single-json \"{0}\"")]
        public string CMD_GET_PLAYLIST_VIDEOS {
            get {
                return ((string)(this["CMD_GET_PLAYLIST_VIDEOS"]));
            }
            set {
                this["CMD_GET_PLAYLIST_VIDEOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--no-playlist --skip-download --get-title --no-warnings \"{0}\"")]
        public string CMD_GET_TITLE {
            get {
                return ((string)(this["CMD_GET_TITLE"]));
            }
            set {
                this["CMD_GET_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.youtube.com/watch?v=")]
        public string BASE_URL {
            get {
                return ((string)(this["BASE_URL"]));
            }
            set {
                this["BASE_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%userprofile%\\Music")]
        public string DEFAULT_SAVEDIR {
            get {
                return ((string)(this["DEFAULT_SAVEDIR"]));
            }
            set {
                this["DEFAULT_SAVEDIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("730")]
        public int LIST_FORM_WIDTH {
            get {
                return ((int)(this["LIST_FORM_WIDTH"]));
            }
            set {
                this["LIST_FORM_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("805")]
        public int LIST_FORM_MAX_HEIGHT {
            get {
                return ((int)(this["LIST_FORM_MAX_HEIGHT"]));
            }
            set {
                this["LIST_FORM_MAX_HEIGHT"] = value;
            }
        }
    }
}
